---
title: "Explore the data6"
author: "Yu"
date: "2024-06-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cifti)
library(dbicc)
library(corrplot)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(CovTools)
```


## load full_data_list
```{r}
load("/Users/yu/Desktop/24 Summer/fMRI/02_explore_data/full_data_list.rda")
```


## Select target session, time points, and ROIs. 
```{r}
# Define the function.
filter_data = function(data_list, target_sessions, start_time_point, end_time_point, target_ROI = NULL) {
  filtered_data_list = lapply(data_list, function(item) {
    if (item$session %in% target_sessions) {
      data_subset <- item$data[start_time_point:end_time_point, ]
      colnames(data_subset) = item$Parcel
      
      if (!is.null(target_ROI)) {
        data_subset = data_subset[, target_ROI, drop = FALSE]
      }
      
      df = as.data.frame(data_subset)
      df$subject = item$subject
      df$session = item$session
      df = df %>% select(-subject, -session)
      return(df)
    } else {
      return(NULL)
    }
  })
  
  filtered_data_list = Filter(Negate(is.null), filtered_data_list)
  return(filtered_data_list)
}

# Select target session, time points, and ROIs.
target_sessions = sprintf ("ses-func%02d", 1:10)
start_time_point = 1
end_time_point = 818
target_ROI = NULL  # Set particular ROIs if needed: c("R_V1_ROI", "R_MST_ROI", "R_V6_ROI")

filtered_data_list <- filter_data(data_list, target_sessions, start_time_point, end_time_point, target_ROI)

```

## delete the subject 08
```{r}
filtered_data_list <- filtered_data_list[-(71:80)]
```


##  matrix distance computation (using mdist)
```{r mdist}
# mdist function
mdist <- function(datalist, method=c("f")) {
    dmat<-matrix(0,length(datalist),length(datalist))
    
    for (i in 2:length(datalist)) for (j in 1:(i-1)){
        if (method=="r"){
            v1<-datalist[[i]][lower.tri(datalist[[i]], diag = FALSE)]
            v2<-datalist[[j]][lower.tri(datalist[[j]], diag = FALSE)]
            r<-cor(v1,v2)
            dmat[i,j]=dmat[j,i]=sqrt(1-r)
        } else if (method=='l1'){
            dmat[i,j]=dmat[j,i]=sum(abs(datalist[[i]]-datalist[[j]]))
        } else {
            dmat[i,j]=dmat[j,i]=norm(datalist[[i]]-datalist[[j]],type=method)
        }
    }
    return(dmat)
}

# compute correlation matrices
cor_data_list <- lapply(filtered_data_list,cor)

# compute the matrix of distances among the correlation matrices
distmat_l2 <- mdist(cor_data_list)
distmat_l1 <- mdist(cor_data_list, "l1")
distmat_root <- mdist(cor_data_list, "r")
```

## distance plot
```{r,  fig.height = 5, fig.width = 7}
plot_distance_matrix <- function(distmat, title) {
  distmat_df <- as.data.frame(as.table(as.matrix(distmat)))
  names(distmat_df) <- c("Var1", "Var2", "Distance")
  distmat_df$Var2 <- factor(distmat_df$Var2, levels = rev(levels(distmat_df$Var2)))

  colors <- colorRampPalette(c("white", "blue"))(100)

  p <- ggplot(distmat_df, aes(Var1, Var2, fill = Distance)) +
    geom_tile() +
    scale_fill_gradientn(colors = colors) +
    theme_minimal() +
    labs(title = title, x = NULL, y = NULL) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
          axis.text.y = element_blank(), axis.ticks.y = element_blank())

  return(p)
}

plot_distance_matrix(distmat_l2, "Distance Matrix method l2")
plot_distance_matrix(distmat_l1, "Distance Matrix method l1")
plot_distance_matrix(distmat_root, "Distance Matrix method root")
```

## standardize 
```{r}
normalize_matrix <- function(matrix) {
  mean_val <- mean(matrix)
  sd_val <- sd(matrix)
  (matrix - mean_val) / sd_val
}

distmat_l1_norm <- normalize_matrix(distmat_l1)
distmat_l2_norm <- normalize_matrix(distmat_l2)
distmat_root_norm <- normalize_matrix(distmat_root)

plot_distance_matrix(distmat_l2_norm, "Distance Matrix method l2")
plot_distance_matrix(distmat_l1_norm, "Distance Matrix method l1")
plot_distance_matrix(distmat_root_norm, "Distance Matrix method root")
```

## Compute the reliability  

```{r dbicc}
dm2icc(distmat_l2,9,10)
dm2icc(distmat_l1,9,10)
dm2icc(distmat_root,9,10)
```

## matrix distance computation (using CovDist)
```{r}
## transform to 3d array
p <- ncol(cor_data_list[[1]])
N <- length(cor_data_list)

cor_array = array(0, dim = c(p, p, N))

for (i in 1:N) {
  cor_array[,,i] <- cor_data_list[[i]]
}

# check positive definite indices
non_positive_definite_indices <- c() 

for (i in seq_len(dim(cor_array)[3])) {
  eigenvalues <- eigen(cor_array[,,i])$values
 
  if (any(eigenvalues <= 0)) {
    non_positive_definite_indices <- c(non_positive_definite_indices, i)
  }
}

print(non_positive_definite_indices) # 33 74 77 82 are not positive definite
```

## adjust to positive definite
```{r}
# define a funtion
adjust_to_positive_definite <- function(matrix) {

    min_eigenvalue <- min(eigen(matrix)$values)
    
    if (min_eigenvalue <= 0) {
        adjustment_value <- abs(min_eigenvalue) + 0.01  # plus 0.01
        matrix <- matrix + diag(adjustment_value, nrow = nrow(matrix))
    }
    return(matrix)
}

# adjust slice 33, 74, 77, 82
non_positive_def_indices <- c(33, 74, 77, 82)
for (i in non_positive_def_indices) {
    cor_array[,,i] <- adjust_to_positive_definite(cor_array[,,i])
}

# check positive definite
for (i in non_positive_def_indices) {
    print(all(eigen(cor_array[,,i])$values > 0))
}
```



## get pairwise distance and reliability
```{r eval = FALSE}
distance_methods <- c("AIRM", "Bhattacharyya", "Cholesky", "Euclidean", "Hellinger", "JBLD", "KLDM", "LERM", "Procrustes.SS", "Procrustes.Full", "PowerEuclidean", "RootEuclidean")

results <- data.frame(Method = character(), Reliability = numeric(), stringsAsFactors = FALSE)

for (method in distance_methods) {
  dist_matrix <- CovDist(cor_array, method = method)
  
  reliability_score <- dm2icc(dist_matrix, 9, 10)
  
  results <- rbind(results, data.frame(Method = method, Reliability = reliability_score))
}

print(results)
```

```{r}
# Method         Reliability
# AIRM            0.1825003
# Bhattacharyya   NaN
# Cholesky        0.3621463
# Euclidean       0.4538179
# Hellinger       NaN
# JBLD            NaN
# KLDM            0.6667029
# LERM            0.220661
# Procrustes.SS   0.4242606
# Procrustes.Full 0.4571571
# PowerEuclidean  Error
# RootEuclidean   0.4579008
```

  







